In [1]:
import json
import operator
import plotly
import plotly.plotly as py
import plotly.figure_factory as ff
import plotly.graph_objs as go
import pandas as pd
import random
import pylab
import matplotlib.pyplot as plt
import numpy as np
from difflib import get_close_matches
from collections import defaultdict

In [2]:
plotly.tools.set_credentials_file(username='KavyaP', api_key='MszYFcAggAFUAOdZ92Wx')

In [3]:
data = []
for line in open('business.json','r'): 
     data.append(json.loads(line))

In [4]:
x =[]
for d in data: # get line in data i.e. each business
    if (d['stars'] ): # check that they have star review
        cat = d['categories'] # save categories to list
        for c in cat: # for each business
            if (c == 'Restaurants'): # check that it is a restaurant
                x.append(d)

In [5]:
# Average stars for all restaurants
stars = 0
for i in range(len(x)):
    stars += x[i]['stars']
avg_stars = stars/len(x)
print stars
print avg_stars

188770.0
3.45618660515


# Average star rating by feature

In [10]:
stars_each = np.array([0,0,0,0,0,0]).astype(float)
len_each = np.array([0,0,0,0,0,0]).astype(float)


for num, business in enumerate(x):
    for cat in x[num]['attributes']:
        if 'BusinessAcceptsCreditCards' in x[num]['attributes']:
            if x[num]['attributes']['BusinessAcceptsCreditCards'] == True:
                stars_each[0] += x[0]['stars'] 
                len_each[0] += 1
        if 'WheelchairAccessible' in x[num]['attributes']:
            if x[num]['attributes']['WheelchairAccessible'] == True:
                stars_each[1] += x[1]['stars'] 
                len_each[1] += 1
        if 'HappyHour' in x[num]['attributes']:
            if x[num]['attributes']['HappyHour'] == True:
                stars_each[2] += x[2]['stars'] 
                len_each[2] += 1
        if 'HasTV' in x[num]['attributes']:
            if x[num]['attributes']['HasTV'] == True:
                stars_each[3] += x[3]['stars'] 
                len_each[3] += 1
        if 'RestaurantsGoodForGroups' in x[num]['attributes']:
            if x[num]['attributes']['RestaurantsGoodForGroups'] == True:
                stars_each[4] += x[4]['stars'] 
                len_each[4] += 1
        if 'BusinessParking' in x[num]['attributes']:
            if x[num]['attributes']['BusinessParking']['garage'] or x[num]['attributes']['BusinessParking']['lot'] or x[num]['attributes']['BusinessParking']['street'] == True:
                stars_each[5] += x[5]['stars'] 
                len_each[5] += 1

avg_each_stars = stars_each/len_each

In [11]:
print stars_each
print len_each

avg_each_stars

[2813191.5 1537312.   487674.  1476737.5 2305788.  1855696.5]
[803769. 384328. 108372. 421925. 768596. 530199.]


array([3.5, 4. , 4.5, 3.5, 3. , 3.5])

In [12]:
labels = ['BusinessAcceptsCards','WheelchairAccessible', 'HappyHour','HasTV','RestaurantGoodForGroups','BusinessParking']
data = [go.Bar(x=labels,y=avg_each_stars,
               marker=dict(
                   color='rgb(158,202,225)',
                   line=dict(
                       width=2))),]
layout = go.Layout(title='Average Star Rating by Feature')
fig = go.Figure(data=data, layout=layout)

In [13]:
plotly.offline.plot(fig, filename='average star rating by feature')

/Users/binhnguyen/anaconda2/lib/python2.7/site-packages/plotly/offline/offline.py:459: UserWarning:

Your filename `average star rating by feature` didn't end with .html. Adding .html to the end of your file.



'file:///Users/binhnguyen/Google Drive/Courses/ECE 180/Team Project/ECE180Team11/average star rating by feature.html'

In [14]:
py.iplot(fig)

# Analysis

In [15]:
def feature(datum):
    '''
    :param: datum, yelp review item
    :type: dict
    
    '''
    feat = [1]
    attributes = datum['attributes']
    
    if 'BusinessAcceptsCreditCards' in attributes:
        if attributes['BusinessAcceptsCreditCards'] == True:
            feat.append(1)
        else:
            feat.append(0)
    else:
        feat.append(random.randint(0, 1))
        
        
    if 'WheelchairAccessible' in attributes:
        if attributes['WheelchairAccessible'] == True:
            feat.append(1)
        else: 
            feat.append(0)
    else:
        feat.append(random.randint(0, 1))
        
        
    if 'HappyHour' in attributes:
        if attributes['HappyHour'] == True:
            feat.append(1)
        else:
            feat.append(0)
    else:
        feat.append(random.randint(0, 1))
        
        
    if 'HasTV' in attributes:
        if attributes['HasTV'] == True:
            feat.append(1)
        else:
            feat.append(0)
    else:
        feat.append(random.randint(0, 1))
        
        
    if 'RestaurantsGoodForGroups' in attributes:
        if attributes['RestaurantsGoodForGroups'] == True:
            feat.append(1)
        else:
            feat.append(0)
    else:
        feat.append(random.randint(0, 1))
        
        
    if 'RestaurantsPriceRange2' in attributes:
        feat.append(attributes['RestaurantsPriceRange2'])
    else:
        feat.append(random.randint(1,4))
        
        
    if 'BusinessParking' in attributes:
        if (attributes['BusinessParking']['garage'] or attributes['BusinessParking']['lot'] or attributes['BusinessParking']['street']):
            feat.append(1)
        else:
            feat.append(0)
    else:
        feat.append(random.randint(0,1))
        
    return feat

In [16]:
[feature(d) for d in x]

[[1, 1, 1, 1, 1, 1, 2, 1],
 [1, 1, 0, 0, 0, 1, 3, 0],
 [1, 1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 0, 1, 1, 0],
 [1, 1, 0, 1, 0, 0, 3, 1],
 [1, 1, 1, 1, 0, 1, 2, 1],
 [1, 1, 0, 1, 1, 1, 2, 1],
 [1, 1, 1, 0, 0, 1, 2, 1],
 [1, 1, 0, 1, 1, 1, 4, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 2, 1],
 [1, 1, 0, 0, 0, 0, 2, 1],
 [1, 1, 1, 1, 1, 1, 2, 1],
 [1, 1, 1, 0, 0, 1, 2, 1],
 [1, 1, 0, 1, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 1, 2, 1],
 [1, 1, 0, 1, 0, 1, 3, 0],
 [1, 1, 1, 1, 1, 1, 2, 1],
 [1, 1, 1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 1, 2, 1],
 [1, 1, 0, 1, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 1, 2, 1],
 [1, 1, 1, 1, 0, 1, 2, 0],
 [1, 0, 0, 1, 0, 0, 1, 0],
 [1, 1, 1, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 0, 0, 2, 1],
 [1, 1, 0, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 1, 2, 0],
 [1, 1, 1, 1, 1, 1, 2, 1],
 [1, 1, 1, 0, 0, 0, 3, 1],
 [1, 0, 1, 0, 0, 1, 3, 0],
 [1, 1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 1, 1, 2, 1],
 [1, 0, 0, 0, 0, 1, 2, 0],
 